### ISSUE TITLE
[Compilers]

### ISSUE THREAD

**Issue by bxpana** [zkSync-Community/zkync-developers#3]
### Discussed in https://github.com/zkSync-Community/zkync-developers/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **bxpana** May 24, 2023</sup>
### Which compiler are you using?

- [X] zksolc
- [ ] zkvyper

### Which version of Solidity or Vyper?

10

### zksolc/zkvyper version?

55

### Explain the issue

```bash
...
No
```

### Link to your repo?

_No response_</div>

**Comment by uF4No** [comment]
solved
